import React from 'react';
import '../styles/Theory.css';
import Footer from '../components/Footer';

const Theory = () => {
  return (
    <main className="theory-page">
      <header className="theory-header">
        <h1>My theory</h1>
        <p>An in-depth exploration into NetArt</p>
      </header>
      <section className="theory-section">
        <article>
        <h2>Critical Analysis of Net/Web Art</h2>
          <p>The landscape of digital art is one that is ever evolving, through which, net art has emerged as a pivotal genre that redefines the interactions between the viewer and the artworks to expand the boundaries of narrative and expression. The net art that has caught my personal interest is “My Boyfriend Came Back From The War'' (MBCBFTW) by the Russian artist Olia Lialina in 1996. The net art was created in the early days of the internet which delved into the themes of personal trauma and societal disconnection of someone that returned from a war through the usage of the medium’s inherent properties of interactivity, fragmentation and networked communication. "Net Art, Post-internet Art, New Aesthetics: The Fundamentals of Art on the Internet," noted that net art transforms the traditional art experience by emphasising the viewer’s role in the navigation of the artworks narrative which I think is the perfect medium for an exploration of one’s personal traumas suffered through a war and their disconnect from society when they return making it so that they’ll never be able to fully integrate into a peaceful life again.</p>
          <p>In comparison to traditional art, the internet as a medium allows for unique capabilities such as its interactivity, connectivity and potential for non-linear storytelling which Olia Lialina’s "My Boyfriend Came Back From The War" utilised perfectly in creating a multi-layered narrative that allowed the viewers to engage with the artwork in a personal way. In "My Boyfriend Came Back From The War", the artwork’s interactivity is not merely a feature, but instead, it is a fundamental part of the artwork for the viewer to experience, the layout of the net art is structured as a series of black and white framed images that are distorted in one way or another and text blocks that branches off into different narrative paths the viewer can click through at their own pace to create their own narrative for the artwork. This form of navigation of "My Boyfriend Came Back From The War" mimics the process of memory recall and fragmented storytelling of that of a traumatised and broken individual returning from a war, the distorted and uncanny images shows the disconnect from reality caused by PTSD and the narrative the viewer can click through shows a conversation of a returning soldier and his partner, where it gradually reveals to the viewer the strains on their relationship caused by his trauma and his struggles to hold onto reality and society.</p>
          <p>The usage of the internet for the artwork also creates a form of networked communication between the artwork and the viewer, where each choice made by the viewer in their navigation of the frames creates a unique narrative path, which can lead to emotions of isolation or misunderstanding for the viewer, which is central to the artwork’s exploration of societal disconnect and the struggles to maintain personal relationships while suffering from PTSD. Lialina’s usage of the interconnected nature of the internet allowed her to create a universal aspect to these experiences rather than just the personal. The theoretical framework mentioned in "Net Art, Post-internet Art, New Aesthetics: The Fundamentals of Art on the Internet" supports the idea that net art transforms the art experience by emphasising the role of the viewer as they interact with the narrative of the artwork on a personal level. In Lialina’s work, the viewer’s interaction is crucial as they literally build their own narratives through their own choices as they progress through the story, this form of active participation from the viewer forces them to confront and understand the complexities and the various struggles one has to face when returning from a war as the net art is not just telling a story to the viewer, rather it forces them to live through the bitter reality that a war veteran has to face, thus creating a whole new experience that passive engagement of the traditional art cannot deliver.</p>
          <p>In "My Boyfriend Came Back From The War," the material modality is represented through the digital interface, that being the HTML frames on the web browser, this choice of medium fundamentally shapes the interactions between the artwork and viewer. Unlike the traditional canvas or physical installations, the digital code and browser window of net art serves both as the canvas of the artwork, but also the narrative device which in a way puts the viewer as the creator of their own artwork and narrative as they progress through the fragmented storytelling. In the lecture slide “Net/Web art” discussed “how and why these material objects function as an interface of communication?" Which in "My Boyfriend Came Back From The War," the digital format allows the fragmentation and interactivity that are crucial for the artworks impact, allowing the narrative to unfold in a non-linear fashion that allows the viewer to experience a story of their own making while also perfectly mimics the process of dealing with fragmented and distorted memories of PTSD as the mind attempts to protect itself from the trauma of the past. The sensorial experience of "My Boyfriend Came Back From The War," is conveyed through the visuals of the distorted black and white images and the textual elements displayed on the screen. The images and texts ensure that the viewer is not just watching a story being told, but rather actively engaging with the artwork by creating their own narratives as they click on the text to advance the story of their choosing. The spatiotemporal modality in Lialina’s artwork is defined by the placement of the text and images across the screen through multiple frames and the temporal control the viewer has as they navigate these frames, each clicks changes and reshapes the spatial layout of the narrative and the pace of the story is controlled by the viewer as they click through the texts. This modality reflects the non-linear nature of memory recall, especially from someone that suffers from PTSD as they deal with the disjointed and often blurred memories being a side effect of the mind’s attempt to protect itself from trauma. Finally the semiotic modality is deeply embedded in the fragmented dialogues of "My Boyfriend Came Back From The War," where the separation of the images and the non-linear progression of the story using the sign systems of language and images to create a narrative that shows the confusion and distortion experienced by those dealing with heavy trauma. This requires the viewers to interpret signs of both the internet as the medium and the content of the narrative, as mentioned in the lecture slides “engaging with media products because they mean something.”
          </p>
          <p>Olia Lialina’s work serves as a pivotal example of early net art that combines both the technical and conceptual frameworks of the internet. With insights from 'Net Art, Post-internet Art, New Aesthetics' Lialina’s artwork engages with the reconfiguration of informations in open networks as well as the development of “an artistic language on the internet.” (DANAE, 2019) This is clear in how the artwork employs the use of hyperlinks and multiple frames in order to create a fragmented narrative structure which allows the viewers to explore the story however they want in a non-linear fashion, this structure also perfectly mimics the fragmented mind of a traumatised individual and their non-linear process of memory recall, thus enhancing the viewer’s understanding as they experience the psychological landscape of PTSD. In David Carrier’s analysis, he highlighted how the internet has transformed the way contemporary visual artworks are created and perceived, where he noted that the reproduction and dissemination methods of the internet have fundamentally altered our interaction and perception of art with the move from physical to digital. This shit is critical in understanding Lialina’s work, where the internet not only serves as a medium for the artwork, but rather it becomes a critical component of the artwork’s conceptual framework in delivering its messages and experience and being accessible by a global audience. The fragmented and interactive nature of "My Boyfriend Came Back From The War," as highlighted in both articles serves to engage the viewers not only just visually, but rather on a cognitive and emotional level through allowing the viewer to choose their own path in the story and uncover pieces of the narrative mirrors that of a traumatised individual attempting to piece their life and sanity back together. This way of interaction presented by the artwork allows for a deeper emotional engagement with the experience presented and encourages the personal reflections of the viewer making this artwork a powerful and accurate look into the struggles and recovery from trauma as well as the difficulties to maintain personal relationships as one loses touch with reality.</p>
          <p>Olia Lialina’s "My Boyfriend Came Back From The War" stands as a profound and pivotal exploration and example of the potential of net art to delve into complex and deeply human experiences through the digital medium. This artwork employs the inherent interactivity, fragmentation and networked communication aspects of the internet to craft a narrative experience that vividly portrays the psychological battle with trauma and the struggles to reintegrate into society faced by war veterans, this is not only a prolific issue faced by countless people in the world, but with today’s geopolitical climate, it has become even more relevant as wars waged on across the world and the prospect of a third world war grows ever closer to becoming a reality. Through its innovative use of the digital space and viewer interaction especially being created at the very infancy of the internet, Lialina has not only told a story, but rather created an environment where the audience became an integral part of the narrative process as they created their own story of a disjointed and fragmented experience of a recovering PTSD veteran. This artwork not only serves as a prominent reminder of the ever evolving relationship between technology and art, but also offers a critical perception on the role of art in society as it encourages viewers to reflect on the impacts of war and the power of art to communication those realities allowing for a deeper understanding for the average individuals of the horrors of war.</p>
        </article>
        <article>
        <p>References:</p>

        <p>Carrier, D. (2020). The Work of Art in the Age of the Internet. [online] Hyperallergic. Available at: https://hyperallergic.com/563938/the-work-of-art-in-the-age-of-the-internet/ [Accessed 24 Apr. 2024].</p>
        <p>DANAE (2019). Net Art, Post-internet Art, New Aesthetics: The Fundamentals of Art on the Internet. [online] Medium. Available at: https://medium.com/danae/net-art-post-internet-art-new-aesthetics-the-fundamentals-of-art-on-the-internet-55dcbd9d6a5 [Accessed 24 Apr. 2024].</p>
        <p>Geyser, H. 2024. Art on the Internet, 14 September. Lecture notes (WSOA4088A). University of Witwatersrand, Johannesburg.</p>
        <p>Geyser, H. 2024. internet-art-internetart. Lecture notes (WSOA4088A). University of Witwatersrand, Johannesburg.</p>
        <p>‌Rhizome.org. (2024). My Boyfriend Came Back from the War | Net Art Anthology. [online] Available at: https://sites.rhizome.org/anthology/lialina.html [Accessed 24 Apr. 2024].</p>
        </article>
        <article>
          <h2>Net Art planning</h2>
          <p>For my net art I have looked at My Boyfriend Came Back from the War (MBCBFTW) by Olia Lialina which was the piece that I have researched for my analysis essay as well. MBCBFTW was created in the infancy of the internet and HTML where the author had utilised HTML to create a choose your own adventure style storytelling where the user would click on whichever button or image they want on the screen to progress through the storytelling of the art piece which was the struggles of someone that suffers PTSD from a war and the hardships they faced to reintegrate into society.</p>
          <section className="netart-images">
            <a href="https://www.artsy.net/artwork/olia-lialina-my-boyfriend-came-back-from-the-war-1" className="netart-image image1">
              <section className="overlay">
                <h3 className="text-title">My Boyfriend Came Back from the War</h3>
                <p className="text-description">My Boyfriend Came Back from the War, 1996 by Olia Lialina</p>
              </section>
            </a>
            <a href="https://anthology.rhizome.org/starrynight" className="netart-image image2">
              <section className="overlay">
                <h3 className="text-title">Starry Night</h3>
                <p className="text-description">Starry Night, 1999 by Alex Galloway, Mark Tribe and Martin Wattenberg.</p>
              </section>
            </a>
          </section>
          <p>Another net art I looked into was Starry Night, 1999 by Alex Galloway, Mark Tribe and Martin Wattenberg. The artwork was created as an artistic archive for Rhizome's email discussion list for artists that worked on different and new forms of media. Each star on the net art is an archieved email and the user could select keywords which would from different constellations by connecting emails that are related to the keyword together.</p>
          <p>For my net art I'd like to create a space themed artwork that users can interact with easily like the simplicity of MBFCBFTW which can be navigated with just a mouse while drawing up the constellation idea from Starry Night where the user could navigate/explore the vastness of the universe and understand just how little we are compared to the observable universe let alone the unobserved universe.</p>
          <p>On the technical side, I plan on making randomised dots to be created around the page and then connect them together with lines to mimic the looks of a sci-fi star map, when the user click on a dot, the entire 'map' would randomise. I want to do this because the overall theme of my website is a fictional space journey where humanity travels the stars and create new colonies, however space is a very vast place and each time you move a location, your perspective of the star changes just like when the viewer click on a dot, the entire map changes.</p>
          <p>My main concern for the technical side is to make sure that the lines connects correctly once the 'stars' dots randomise so that the entire artwork functions correctly no matter how many times the viewer clicks on the dots.</p>
        </article>

        <article>
          <h2>Net Art Rationale - The infinity</h2>
          <p>My net art that I have dubbed "The infinity" is a series of dots that are randomly placed around the net art page, each dots are interconnected by several lines. The artwork itself is larger than the screen so the user can use both the vertical and horizontal scrolls to explore the entire artwork, the reason I chose this size is to create a claustrophobic feeling as the user could never fully view the entire artwork at once, only a section that's filled with lines and dots, this mirrors the reality of humanity gazing upon the infinite universe where what we could observe is already unimaginably vast, yet it pales in comparison with everything out there that we can not observe.</p>
          <section className="netart-images">
            <article className="netart-image image3"></article>
            <article className="netart-image image4"></article>
          </section>
          <p>When the user click on a dot, the entire artwork shuffles around to create a brand new perspective, this was done as to show that once we are able to explore the stars, the constellations that we know so well will change as the stars' position will change based on wherever you are in the vast galaxy, the night sky will not be the same for someone that is living on a planet light years away from the Earth. Each line connecting the distant dots signifies the connection of humanity as a whole no matter where we are in the infinite universe.</p>
        </article>
      </section> 
      <Footer />
    </main>
  );
};

export default Theory;
